function score() {
    d=10
    t1=document.getElementById("t1").value
    t2=document.getElementById("t2").value
    t3=document.getElementById("t3").value
    t4=document.getElementById("t4").value
    t5=document.getElementById("t5").value
    t6=document.getElementById("t6").value
    t7=document.getElementById("t7").value
    r1=document.getElementById("y1").checked
    r2=document.getElementById("y2").checked
    r3=document.getElementById("ym3").checked||document.getElementById("n3").checked
    r4=document.getElementById("y4").checked
    r5=document.getElementById("y5").checked
    r6=document.getElementById("y6").checked
    r7=document.getElementById("y7").checked
    r8=document.getElementById("y8").checked
    r9=document.getElementById("y9").checked
    r10=document.getElementById("n10").checked
    r11=document.getElementById("y11").checked||document.getElementById("n11").checked
    r12=document.getElementById("y12").checked
    s=document.getElementById("s").value
    m=document.getElementById("h").checked||document.getElementById("j").checked||document.getElementById("ra").checked
   
    if(t1!=""){
        d=d+1
    }
    else{
        d=d-1
    }
    if(t2!=""){
        d=d+1
    }
    else{
        d=d-1
    }
    if(t3!=""){
        d=d+1
    }
    else{
        d=d-1
    }
    if(t4!=""){
        d=d+1
    }
    else{
        d=d-1
    }
    if(t5!=""){
        d=d+1
    }
    else{
        d=d-1
    }
    if(t6!=""){
        d=d+1
    }
    else{
        d=d-1
    }
    if(t7!=""){
        d=d+1
    }
    else{
        d=d-1
    }
    if(r1==true){
        d=d+1
    }
    else{
        d=d-1
    }
    if(r2==true){
        d=d+1
    }
    else{
        d=d-1
    }
    if(r3==true){
        d=d+1
    }
    else{
        d=d-1
    }
    if(r4==true){
        d=d+1
    }
    else{
        d=d-1
    }
    if(r5==true){
        d=d+1
    }
    else{
        d=d-1
    }
    if(r6==true){
        d=d+1
    }
    else{
        d=d-1
    }
    if(r7==true){
        d=d+1
    }
    else{
        d=d-1
    }
    if(r8==true){
        d=d+1
    }
    else{
        d=d-1
    }
    if(r9==true){
        d=d+1
    }
    else{
        d=d-1
    }
    if(r10==true){
        d=d+1
    }
    else{
        d=d-1
    }
    if(r11==true){
        d=d+1
    }
    else{
        d=d-1
    }
    if(r12==true){
        d=d+1
    }
    else{
        d=d-1
    }
    if(s>6){
        d=d+1
    }
    else{
        d=d-1
    }
    if(m==true){
        d=d+1
    }
    else{
        d=d-1
    }
    localStorage.setItem('myVar', d);
    window.location.href = 'thks.html';

}
function score2(){
    d=localStorage.getItem('myVar')
    document.getElementById('l').innerHTML=d
    
}

function print(){
    a=document.getElementById("ag").value
    document.getElementById("r").value=a
}
function pic(){
    alert("open with pc for better vue ")
}
